#!/usr/bin/env bash
# Run the named Cloudflare Tunnel that publishes the remote machine.
#
#   cloudflared  --->  Cloudflare edge  --->  Access authentication
#                  --->  /websockify  -->  websockify 6080  --->  RFB 5900
#                  -->  everything else  -->  the RAG Agents app on 8000
#
# The connection is outbound, so nothing has to be opened on the Codespace and
# no GitHub forwarded port is involved at all.  That is the whole point: the
# only way in is a hostname that requires a Cloudflare Access login.
#
# One hostname serves both the app and the screen on purpose.  Access hands the
# browser a first-party cookie for that hostname, so the noVNC WebSocket
# upgrade carries it automatically.  A screen on a *different* hostname than the
# app would be a cross-site request, and browsers increasingly drop those
# cookies -- the user would be bounced back to the login page mid-session.
set -uo pipefail

CODESPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CODESPACE_DIR/env.sh"

require_cmd cloudflared || exit 1

if [ -z "$CF_TUNNEL_TOKEN" ]; then
  cat >&2 <<'EOF'
[computer] FATAL: CF_TUNNEL_TOKEN is not set.

  This is a Codespace secret, not a file in the repo.  Add it with:
    Settings > Codespaces > your codespace > Codespaces secrets
      CF_TUNNEL_TOKEN  =  <the install command's token>

  Get the token from Cloudflare: Zero Trust > Networks > Tunnels > your
  tunnel > Configure a public hostname, then "Install and run a connector"
  shows the token.  Never commit it.
EOF
  exit 1
fi

if [ ! -f "$CF_CONFIG" ]; then
  if [ -z "$COMPUTER_HOSTNAME" ]; then
    cat >&2 <<EOF
[computer] FATAL: no tunnel config at $CF_CONFIG and COMPUTER_HOSTNAME is unset.

  Either copy the example and edit it:
    cp $CODESPACE_DIR/cloudflared/config.yml.example $CF_CONFIG
  or set COMPUTER_HOSTNAME (e.g. computer.example.com) and this script will
  generate the config for you.
EOF
    exit 1
  fi
  mkdir -p "$(dirname "$CF_CONFIG")"
  cat > "$CF_CONFIG" <<EOF
# Generated by codespace/start-tunnel.sh.  Safe to commit: it holds no secrets.
# The credential lives in CF_TUNNEL_TOKEN, which is a Codespaces secret.
tunnel: rag-agents-computer
credentials-file: /dev/null
no-autoupdate: true

ingress:
  # The screen.  websockify accepts the upgrade on any path, so /websockify is
  # the stable name the RAG Agents UI connects to.  Cloudflare matches ingress
  # rules in order, and the first one that matches the host *and* path wins.
  - hostname: $COMPUTER_HOSTNAME
    path: ^/websockify(/.*)?$
    service: http://127.0.0.1:$WEBSOCKIFY_PORT
    originRequest:
      # WebSockets must survive Cloudflare's proxy.  noVNC needs this: without
      # it the upgrade is buffered and the screen hangs on "connecting".
      noTLSVerify: true
  # The RAG Agents app itself, so the whole product is one origin behind one
  # Access login.  This also keeps the backend's /ws/screen relay and REST API
  # out of reach until the user is authenticated.
  - hostname: $COMPUTER_HOSTNAME
    service: http://127.0.0.1:$BACKEND_PORT
  # Never let a stray hostname escape to the origin.
  - service: http_status:404
EOF
  log "generated $CF_CONFIG for $COMPUTER_HOSTNAME"
fi

# Refuse to start against a dead origin: a tunnel that accepts connections and
# then 502s looks exactly like a broken screen to the user.
if ! listening "$WEBSOCKIFY_PORT"; then
  log "WARNING: nothing is listening on 127.0.0.1:$WEBSOCKIFY_PORT yet."
  log "         the tunnel will accept connections but serve 502s."
  log "         run codespace/start-computer.sh first."
fi

log "starting cloudflared tunnel"
log "  config  $CF_CONFIG"
log "  screen  https://$COMPUTER_HOSTNAME/websockify  (Access required)"
log "  app     https://$COMPUTER_HOSTNAME              (Access required)"

# A named tunnel authenticated by token: no cert.pem, no key in the repo, and
# --token wins over any config credential file.
exec cloudflared tunnel \
  --no-autoupdate \
  --config "$CF_CONFIG" \
  run --token "$CF_TUNNEL_TOKEN"
